name: Build image
on:
  workflow_call:
    inputs:
      docker-file-path:
        required: true
        type: string 
      tag-name:
        required: true
        type: string
jobs:
  build_push_image:
    name: ${{docker-file-path}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set enviroment variables
        run: cd ${{github.workspace}} && source set_env.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5

        with:
          context: ${{docker-file-path}}
          push: true
          tags: ${{tag-name}}


