name: Deployment
on:
  workflow_dispatch:
    
jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - name: Feed API
        uses: /.github/workflows/build_image.yml
        with:
          docker-file-path: ./udagram-api-feed
          tag-name: tvu51/udagram-api-feed:latest

      - name: User API
        uses: /.github/workflows/build_image.yml
        with:
          docker-file-path: ./udagram-api-user
          tag-name: tvu51/udagram-api-user:latest

      - name: Frontend
        uses: /.github/workflows/build_image.yml
        with:
          docker-file-path: ./udagram-frontend
          tag-name: tvu51/udagram-frontend:latest

      - name: Reverse proxy
        uses: /.github/workflows/build_image.yml
        with:
          docker-file-path: ./reverseproxy
          tag-name: tvu51/reverseproxy:latest
